### PR TITLE
Update meshing.py

### PR DESCRIPTION
**Pull request by standardgalactic**
I had to change marching_cubes_lewiner to marching_cubes in order to get this example to work: 

# Start with a mesh neuron
m = navis.example_neurons(1, kind='mesh')

# Skeletonize the mesh
s = navis.skeletonize(m)

# Make dotprops (this works from any other neuron type
dp = navis.make_dotprops(s, k=5)

# Voxelize the mesh
vx = navis.voxelize(m, pitch='2 microns', smooth=1, counts=True)

# Mesh the voxels
mm = navis.mesh(vx.threshold(.5))  # where things broke

# Co-visualize the mesh and the skeleton
fig = navis.plot3d([m, s], color=[(1, 1, 1, .2), 'r'])

Don't know if this would be helpful to anyone else...

### CODE REVIEW

**Comment by schlegelp** [comment]
Hi & thanks for the PR! I'm not sure I follow your changes though:

```Python
# Before
marching_cubes = getattr(measure, 'marching_cubes',
                          getattr(measure, 'marching_cubes_lewiner', None))
# After 
marching_cubes = getattr(measure, 'marching_cubes',
                          getattr(measure, 'marching_cubes', None))
```

The reason for this nested `getattr` is this: `skimage` renamed the `marching_cubes_lewiner` function to `marching_cubes` in the more recent versions (there was a transition period during which both still existed). Hence, we have to look for both functions in case someone still runs an old version of `skimage`. With your changes we are looking for the same function in both `getattr` calls which is not the intention. 

I should note that this line has seen a recent edit in 8d9d26ea273a02a8bc9e669fb85ef041d99a3d23 which fixed a logical bug with the most recent version of `skimage` in which `marching_cubes_lewiner` was finally dropped for good. This commit only lives on Github and has not made it onto PyPI - so you might have encountered that bug? 

Perhaps you could share the traceback of the error you encountered originally?

**Comment by standardgalactic** [comment]
Maybe it's not a bug.  But I had an error message that said something like "measure has no method 'marching_cubes_lewiner' " I found the offending line and removed it and then  removed it. I submitted the pull so it could be seen, but when I read it through I saw the line that said something about it would be depreciated. I was working in blender, and after I removed the "lewiner" I was able to make it work. 

Here is some more code I was running.

PYTHON INTERACTIVE CONSOLE 3.9.2 (default, Mar  1 2021, 08:18:55) [MSC v.1916 64 bit (AMD64)]

Builtin Modules:       bpy, bpy.data, bpy.ops, bpy.props, bpy.types, bpy.context, bpy.utils, bgl, blf, mathutils
Convenience Imports:   from mathutils import *; from math import *
Convenience Variables: C = bpy.context, D = bpy.data

>>> import numpy
>>> import navis
>>> nl = navis.example_neurons()
>>> import navis.interfaces.blender as b3d
>>> h = b3d.Handler()
>>> h.add(n1)
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
NameError: name 'n1' is not defined

>>> h.add(nl)
Import done in 1.59s

>>> 

import bpy
from bpy import data as D
from bpy import context as C
from mathutils import *
from math import *

#~ PYTHON INTERACTIVE CONSOLE 3.9.2 (default, Mar  1 2021, 08:18:55) [MSC v.1916 64 bit (AMD64)]
#~ 
#~ Builtin Modules:       bpy, bpy.data, bpy.ops, bpy.props, bpy.types, bpy.context, bpy.utils, bgl, blf, mathutils
#~ Convenience Imports:   from mathutils import *; from math import *
#~ Convenience Variables: C = bpy.context, D = bpy.data
#~ 
import numpy
import navis
nl = navis.example_neurons()
import navis.interfaces.blender as b3d
h = b3d.Handler()
h.add(n1)
#! Traceback (most recent call last):
#!   File "<blender_console>", line 1, in <module>
#! NameError: name 'n1' is not defined
#! 
h.add(nl)
#~ Import done in 1.59s
#~

**Comment by schlegelp** [comment]
I see! That issue is fixed already and I will be pushing a new version of `navis` including that fix to PyPI shorty.

**Comment by schlegelp** [comment]
Closing since this is fixed.

**Pull request closed without merging**
