### PR TITLE
Graphviz fix

### PR DESCRIPTION
**Pull request by clbarnes**
Adds pygraphviz as an optional dependency and installs that optional dependency for the tests workflow, fixing the current failure on master.

### CODE REVIEW

**Comment by clbarnes** [comment]
Ah, just spotted https://github.com/navis-org/navis/commit/f231f758dae4b36df4295b8397d4815f16ed9f84 . I guess keeping it as an option is still the way to go as it is required for the tests but people who haven't updated python since 2019 can still use navis.

As an aside, 3.7 is [numpy-deprecated](https://numpy.org/neps/nep-0029-deprecation_policy.html), which is a standard much of the scientific ecosystem has started following. That could be justification for navis to follow suit?

**Comment by schlegelp** [comment]
Yes, it's annoying. 

Re dropping support for 3.7: IIRC R (via reticulate) might still use older (3.6, 3.7) versions of Python and I'd be nice if people could still install navis (and hence all downstream packages) without problems.

We could stop testing but still allowing install on 3.7? What do you think?

**Comment by clbarnes** [comment]
It looks like the CI runs against py38 https://github.com/rstudio/reticulate/blob/main/.github/workflows/pkgdown.yaml#L33 (if only for building docs). There don't seem to be any python version-related issues on the reticulate github repo either, so might be in the clear?

**Comment by schlegelp** [comment]
Oh cool. Perhaps a quick check with @jefferis: are you aware of people still using Python 3.7 or lower (via R or otherwise)?

**Comment by clbarnes** [comment]
There will always be people using outdated versions of python ;) and they're welcome to continue using outdated python versions with an outdated navis version...

**Comment by schlegelp** [comment]
So ruthless...

**Comment by jefferis** [comment]
reticulate (the R python interface) uses Python 3.8 as the default since this commit https://github.com/rstudio/reticulate/commit/66d7c72a1bf7ad6049614a5f751df7fae8b432f1 which was part of the 1.2.3 release on CRAN last month. People will have to update their miniconda install manually, but it should now be possible without gymnastics. So upgrading to 3.8 should not cause any serious problems.

More generally I would appreciate trying to keep backward compatibility with earlier python versions for a while. As a non-expert user I find python version management *much* more troubling than other languages that I use.

**Comment by schlegelp** [comment]
FYI: I made a commit that skips the one doctest that requires pygraphviz (and graphviz). Tests pass again in `main`.

**Pull request closed without merging**
