### PR TITLE
NeuronConnector class for connectivity of TreeNeurons

### PR DESCRIPTION
**Pull request by clbarnes**
For converting a bag of neurons with possibly-intersecting connector nodes into a graph or adjacency matrix.

### CODE REVIEW

**Comment by schlegelp** [comment]
This looks useful! I guess the main use case are CATMAID neurons for now? Given that it requires meaningful connector IDs I would suggest making a note in the docstring. Perhaps even a sanity check that throws a warning if a neuron is added with sequential connector IDs?

I'd also add the `NeuronConnector` class to the API page.

**Comment by schlegelp** [comment]
Hi Chris. Sorry, I lost track of this. Happy to merge if ready?

**Comment by clbarnes** [comment]
I've added an integration test so I'm happy that it works now. The merge log looks pretty whacky, though, it's claiming responsibility for a bunch of older commits, possibly because of a rebase.

**Comment by clbarnes** [comment]
Superceded by #133

**Pull request closed without merging**
