### PR TITLE
neuprint: Two fixes

### PR DESCRIPTION
**Pull request by stuarteberg**
The first commit allows the user to access single-resolution "legacy" precomputed meshes, but only if they pass `lod=None`.  Maybe you can suggest a friendlier implementation.

The second commit concerns selecting a URL from the neuroglancer segmentation `source`.  In our neuroglancer links, we sometimes list multiple sources for segment properties, in which case `source` is a list-of-dict.

These have gone through only minimal testing (by hand).  Hopefully I haven't broken anything.

### CODE REVIEW

**Comment by stuarteberg** [comment]
cc @floesche @hoellerj.

**Comment by schlegelp** [comment]
Hi Stuart. Thanks, this looks good to me! If tests pass I'll merge right away. Do you need me to also release a new version to PyPI right away?

**Comment by stuarteberg** [comment]
>Do you need me to also release a new version to PyPI right away?

That's a question for @floesche and @hoellerj

**Comment by floesche** [comment]
No need to do this right now. We can use the commit with fixes in our dependencies. Currently we are using 91671f11462a63fb5ec867f6561c6f65a49d7b54…

**Comment by schlegelp** [comment]
Some tests failed but that's on me from an earlier commit. Merged, thanks for the contribution! Let me know if I can help with what you guys are up to.

**Pull request merged**
