### PR TITLE
Add {read,write}_h5 to API docs

### PR DESCRIPTION
**Pull request by clbarnes**
If these functions are ready for prime time it'd be great to have them on the docs site!

### CODE REVIEW

**Comment by schlegelp** [comment]
Those were my attempt to find a file format that could easily be shared with `nat` (see https://github.com/schlegelp/nat.hdf5). They work (or at least used to work) but have a couple downsides compared to R's `load/save` (slower and larger files). Greg argued (rightfully) that we could just use zip files as containers. Bottom line: they never picked up steam and I think of them as having only academic interest at this point. Do you see a use case for them?

**Comment by clbarnes** [comment]
Just seeking the best way to cache a few thousand neurons pulled from CATMAID, and keep the annotations etc. intact, so that we don't have to pull them from CATMAID every time (it's slow and runs the risk of data changing). Which format would you recommend? I understand that somewhere in the Neuron inheritance you had to manually force some pickle stuff, and pickle isn't ideal for storage anyway.

**Comment by schlegelp** [comment]
> I understand that somewhere in the Neuron inheritance you had to manually force some pickle stuff, and pickle isn't ideal for storage anyway

Are you referring to the `__set/get_state__` methods? 

I would double check to be on the safe side but pickling of neurons should work just fine - after all neurons are always pickled/unpickled when using multiple parallel processes. Pickle is suitable if (a) you don't need to load the data outside of Python and (b) it's short-term storage only (since changes to the neuron structure in future versions of navis might break unpickling).

**Comment by clbarnes** [comment]
Ah if the format is being soft-deprecated then I'll close this. One day we'll have a neuron interchange format...

**Pull request closed without merging**
