### PR TITLE
Vispy extras and docs

### PR DESCRIPTION
**Pull request by clbarnes**
- Provide a `vispy` extra using pyside6
- Provide `vispy-*` extras for all backends
- Document it

Supercedes #86

### CODE REVIEW

**Comment by clbarnes** [comment]
In this remix, any vispy at all is behind an extra (as it has its installation issues and is a heavy dependency for headless contexts), but we at least offer an opinionated default.

**Comment by schlegelp** [comment]
I would suggest also adding a sentence to the README.md too - just so that people who only look at the repo at first know that's an extra step.

Side note: I wonder if it wouldn't make more sense to keep dependencies as is and instead have a `navis[minimal]` which would exclude all but the bare minimum? People who run into issues with the standard install could then try that out. 

I'm OK either way - just wanted to put this second option up for discussion.

**Comment by clbarnes** [comment]
I agree that an explicit minimal install would be better but unfortunately I'm pretty sure it's not possible under python's package metadata standard. Rust has something along those lines - a "default" feature flag which you can choose to disable - but python can only add dependencies with its extras. I suppose that's why they're extras rather than feature flags.

Good point about the README, and I'll dig through for other mentions of vispy too.

**Comment by schlegelp** [comment]
👀  I did a bit of Googling and came up empty handed too. Strange... seems like a useful feature. In that case: feel free to go ahead with this change.

**Comment by clbarnes** [comment]
Remaining failure is just a missing token; if you're happy with the choices and level of documentation, this can go in.

**Comment by schlegelp** [comment]
Go for it!

**Pull request merged**
